wandb:
  entity: null
#  run_id: askkz9i2
  resume: 'auto'

experiment:
    project: "BlockDiff-VLA"
    name: "show-o-demo"
    output_dir: "show-o-demo"

act_step: 10

model:
    framework: "upvla"
    vq_model:
        type: "magvitv2"
        vq_model_name: "showlab/magvitv2"

    showo:
        pretrained_model_path: "showlab/show-o-w-clip-vit-512x512"
        tuned_model_path: "./BlockDiff-VLA-action-10/checkpoint-170000" # set to your local training checkpoint directory
        w_clip_vit: True
        vocab_size: 58498
        llm_vocab_size: 50295
        llm_model_path: './showlab/phi-1_5'
        codebook_size: 8192
        num_vq_tokens: 1024
        num_new_special_tokens: 10  # <|soi|> <|eoi|> <|sov|> <|eov|> <|t2i|> <|mmu|> <|t2v|> <|v2v|> <|lvg|> <|pad|>

    vla:
      num_view: 1 # 1: third 2: third+gripper

    gradient_checkpointing: True

dataset:
    gen_type: "pre"
    und_type: "captioning"
    params:
        batch_size: ${training.batch_size}
        shuffle_buffer_size: 1000
        num_workers: 32
        resolution: 512
        pin_memory: True
        persistent_workers: True

    preprocessing:
        max_seq_length: 576
        resolution: 512
        center_crop: False
        random_flip: False

training:
    clip_pad_tokens: False
    gradient_accumulation_steps: 1
    cond_dropout_prob: 0.0
    batch_size: 20
